name: Email Service Scheduler

on:
  workflow_dispatch: # manual run
  schedule:
    - cron: '0 7 * * *' # 7am UTC daily

jobs:
  run-email-service:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore ./ArasEmailService/ArasEmailService.csproj

    - name: Build project
      run: dotnet build --configuration Release ./ArasEmailService/ArasEmailService.csproj

    - name: Run Email Service
      env:
        Smtp__Host: ${{ secrets.Smtp__Host }}
        Smtp__Port: ${{ secrets.Smtp__Port }}
        Smtp__User: ${{ secrets.Smtp__User }}
        Smtp__Password: ${{ secrets.Smtp__Password }}
        Smtp__SecureSocketOptions: ${{ secrets.Smtp__SecureSocketOptions }}
        ConnectionStrings__DefaultConnection: ${{ secrets.ConnectionStrings__DefaultConnection }}
        GITHUB_ACTIONS: true
      run: dotnet ./ArasEmailService/ArasEmailService/bin/Release/net9.0/ArasEmailService.dll
