name: Email Service Scheduler

on:
  workflow_dispatch: # manual run
  schedule:
    - cron: '0 7 * * *' # 7am UTC daily

jobs:
  run-email-service:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore ./ArasEmailService/ArasEmailService.csproj

    - name: Clean and Build Release
      run: |
        dotnet clean ./ArasEmailService/ArasEmailService.csproj
        dotnet build --configuration Release ./ArasEmailService/ArasEmailService.csproj

    - name: Run Email Service
      env:
        API__URL: ${{ secrets.API__URL }}
        API__USERNAME: ${{ secrets.API__USERNAME }}
        API__ENCRYPTEDPASSWORD: ${{ secrets.API__ENCRYPTEDPASSWORD }}

        SMTP__HOST: ${{ secrets.SMTP__HOST }}
        SMTP__PORT: ${{ secrets.SMTP__PORT }}
        SMTP__USER: ${{ secrets.SMTP__USER }}
        SMTP__PASSWORD: ${{ secrets.SMTP__PASSWORD }}
        SMTP__SECURESOCKETOPTIONS: ${{ secrets.SMTP__SECURESOCKETOPTIONS }}

        DATABASE__CONNECTIONSTRING: ${{ secrets.DATABASE__CONNECTIONSTRING }}
        EMAIL__FROMEMAIL: ${{ secrets.EMAIL__FROMEMAIL }}
        EMAIL__FROMNAME: ${{ secrets.EMAIL__FROMNAME }}
        GITHUB_ACTIONS: true
        run: dotnet run --project ./ArasEmailService/ArasEmailService.csproj --configuration Release
